server:
  port: 8080
spring:
  application:
    name: wantedalways-gateway
  config:
    import:
      - optional:nacos:${spring.application.name}-@profile.name@.yaml
  cloud:
    nacos:
      config:
        server-addr: @nacos.addr@
      discovery:
        server-addr: @nacos.addr@

